name: lithosphere
channels:
    - defaults
    - conda-forge
dependencies:
    - python==3.8
    - pip
    - numpy
    - scipy
    - pandas
    - matplotlib
    - jupyter
    - jupyterlab
    - xarray
    - cartopy
    - netcdf4
    - pygmt
    - cmocean
    # To serve slides
    - livereload
    # Fatiando packages
    - verde==1.6.0
    - boule==0.2.0
    - harmonica==0.2.1
    # To speed up Verde
    - pykdtree
    - numba
